version: "3.8"

services:
#  app:
#    image: 'ibank/ibank-repo:latest'
#    build:
#      context: .
#    container_name: app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iBank
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    network_mode: host
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ibank